name: commit test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: commit test
        if: github.event_name != 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "commit test"
          git push
      - name: get last commit message and sha
        run: |
          git rev-parse HEAD
          git log -1 --pretty=%B
      - name: fetch all remote branches
        run: |
          git fetch --all
          git branch -a
      - name: compare last commit sha with FritzAndFriends/TagzApp main branch
        run: |
          git remote add upstream git@github.com:FritzAndFriends/TagzApp
          git fetch upstream
          git switch -c upstream-main upstream/main
          git log -1 --pretty=%B
          git diff --name-only upstream-main main